export interface EmojiItem {
  emoji: string
  name: string
  keywords: string[]
}

export const emojiCategories: { label: string; items: EmojiItem[] }[] = [
  {
    label: '笑脸与表情',
    items: [
      { emoji: '😀', name: ' grinning face', keywords: ['smile', 'happy', 'grin'] },
      { emoji: '😃', name: ' grinning face with big eyes', keywords: ['smile', 'happy', 'joy'] },
      { emoji: '😄', name: ' grinning face with smiling eyes', keywords: ['smile', 'happy', 'joy'] },
      { emoji: '😁', name: ' beaming face with smiling eyes', keywords: ['smile', 'happy'] },
      { emoji: '😆', name: ' grinning squinting face', keywords: ['laugh', 'happy'] },
      { emoji: '😅', name: ' grinning face with sweat', keywords: ['sweat', 'smile'] },
      { emoji: '🤣', name: ' rolling on the floor laughing', keywords: ['laugh', 'rofl'] },
      { emoji: '😂', name: ' face with tears of joy', keywords: ['laugh', 'tears', 'joy'] },
      { emoji: '🙂', name: ' slightly smiling face', keywords: ['smile'] },
      { emoji: '😊', name: ' smiling face with smiling eyes', keywords: ['smile', 'blush'] },
      { emoji: '😇', name: ' smiling face with halo', keywords: ['angel', 'innocent'] },
      { emoji: '🥰', name: ' smiling face with hearts', keywords: ['love', 'heart'] },
      { emoji: '😍', name: ' smiling face with heart-eyes', keywords: ['love', 'heart', 'eyes'] },
      { emoji: '🤩', name: ' star-struck', keywords: ['star', 'excited'] },
      { emoji: '😘', name: ' face blowing a kiss', keywords: ['kiss', 'love'] },
      { emoji: '😗', name: ' kissing face', keywords: ['kiss'] },
      { emoji: '😚', name: ' kissing face with closed eyes', keywords: ['kiss'] },
      { emoji: '😙', name: ' kissing face with smiling eyes', keywords: ['kiss', 'smile'] },
      { emoji: '🥲', name: ' smiling face with tear', keywords: ['smile', 'cry'] },
      { emoji: '😋', name: ' face savoring food', keywords: ['yum', 'food'] },
      { emoji: '😛', name: ' face with tongue', keywords: ['tongue', 'playful'] },
      { emoji: '😜', name: ' winking face with tongue', keywords: ['tongue', 'playful', 'wink'] },
      { emoji: '🤪', name: ' zany face', keywords: ['crazy', 'zany'] },
      { emoji: '😝', name: ' squinting face with tongue', keywords: ['tongue', 'playful'] },
      { emoji: '🤑', name: ' money-mouth face', keywords: ['money'] },
      { emoji: '🤗', name: ' smiling face with open hands', keywords: ['hug'] },
      { emoji: '🤭', name: ' face with hand over mouth', keywords: ['shh', 'secret'] },
      { emoji: '🫢', name: ' face with open eyes and hand over mouth', keywords: ['surprise'] },
      { emoji: '🫣', name: ' face with peeking eye', keywords: ['peek', 'shy'] },
      { emoji: '🤫', name: ' shushing face', keywords: ['shh', 'quiet'] },
      { emoji: '🤔', name: ' thinking face', keywords: ['think', 'thought'] },
      { emoji: '🫡', name: ' saluting face', keywords: ['salute'] },
      { emoji: '🤐', name: ' zipper-mouth face', keywords: ['zip', 'silent'] },
      { emoji: '🤨', name: ' face with raised eyebrow', keywords: ['skeptical'] },
      { emoji: '😐', name: ' neutral face', keywords: ['neutral'] },
      { emoji: '😑', name: ' expressionless face', keywords: ['blank'] },
      { emoji: '😶', name: ' face without mouth', keywords: ['silent'] },
      { emoji: '😏', name: ' smirking face', keywords: ['smirk', 'smug'] },
      { emoji: '😒', name: ' unamused face', keywords: ['unamused'] },
      { emoji: '🙄', name: ' face with rolling eyes', keywords: ['roll', 'eyes'] },
      { emoji: '😬', name: ' grimacing face', keywords: ['grimace', 'awkward'] },
      { emoji: '😮‍💨', name: ' face exhaling', keywords: ['exhale', 'relief'] },
      { emoji: '🤥', name: ' lying face', keywords: ['liar', 'lie'] },
      { emoji: '😌', name: ' relieved face', keywords: ['relieved'] },
      { emoji: '😔', name: ' pensive face', keywords: ['pensive', 'sad'] },
      { emoji: '😪', name: ' sleepy face', keywords: ['sleepy', 'tired'] },
      { emoji: '🤤', name: ' drooling face', keywords: ['drool'] },
      { emoji: '😴', name: ' sleeping face', keywords: ['sleep', 'zzz'] },
      { emoji: '😷', name: ' face with medical mask', keywords: ['mask', 'sick'] },
      { emoji: '🤒', name: ' face with thermometer', keywords: ['sick', 'fever'] },
      { emoji: '🤕', name: ' face with head-bandage', keywords: ['hurt', 'injury'] },
      { emoji: '🤢', name: ' nauseated face', keywords: ['sick', 'nausea'] },
      { emoji: '🤮', name: ' face vomiting', keywords: ['sick', 'vomit'] },
      { emoji: '🤧', name: ' sneezing face', keywords: ['sneeze', 'sick'] },
      { emoji: '🥵', name: ' hot face', keywords: ['hot', 'sweat'] },
      { emoji: '🥶', name: ' cold face', keywords: ['cold', 'freeze'] },
      { emoji: '🥴', name: ' woozy face', keywords: ['dizzy'] },
      { emoji: '😵', name: ' dizzy face', keywords: ['dizzy'] },
      { emoji: '🤯', name: ' exploding head', keywords: ['explode', 'mind', 'blown'] },
      { emoji: '🤠', name: ' cowboy hat face', keywords: ['cowboy'] },
      { emoji: '🥳', name: ' partying face', keywords: ['party', 'celebrate'] },
      { emoji: '🥸', name: ' disguised face', keywords: ['disguise'] },
      { emoji: '😎', name: ' smiling face with sunglasses', keywords: ['cool', 'sunglasses'] },
      { emoji: '🤓', name: ' nerd face', keywords: ['nerd'] },
      { emoji: '🧐', name: ' face with monocle', keywords: ['monocle'] },
      { emoji: '😕', name: ' confused face', keywords: ['confused'] },
      { emoji: '😟', name: ' worried face', keywords: ['worried'] },
      { emoji: '🙁', name: ' slightly frowning face', keywords: ['sad', 'frown'] },
      { emoji: '😮', name: ' face with open mouth', keywords: ['surprised'] },
      { emoji: '😯', name: ' hushed face', keywords: ['hushed'] },
      { emoji: '😲', name: ' astonished face', keywords: ['shocked', 'astonished'] },
      { emoji: '😳', name: ' flushed face', keywords: ['embarrassed', 'flushed'] },
      { emoji: '🥺', name: ' pleading face', keywords: ['beg', 'plead', 'puppy'] },
      { emoji: '😢', name: ' crying face', keywords: ['cry', 'tear', 'sad'] },
      { emoji: '😭', name: ' loudly crying face', keywords: ['cry', 'sob'] },
      { emoji: '😤', name: ' face with steam from nose', keywords: ['frustrated', 'triumph'] },
      { emoji: '😡', name: ' pouting face', keywords: ['angry', 'rage'] },
      { emoji: '😠', name: ' angry face', keywords: ['angry', 'mad'] },
      { emoji: '🤬', name: ' face with symbols on mouth', keywords: ['curse', 'swear'] },
      { emoji: '😈', name: ' smiling face with horns', keywords: ['devil', 'mischievous'] },
      { emoji: '👿', name: ' angry face with horns', keywords: ['devil', 'angry'] },
      { emoji: '💀', name: ' skull', keywords: ['death', 'skull'] },
      { emoji: '☠️', name: ' skull and crossbones', keywords: ['poison', 'danger'] },
      { emoji: '💩', name: ' pile of poo', keywords: ['poop', 'shit'] },
      { emoji: '🤡', name: ' clown face', keywords: ['clown'] },
      { emoji: '👹', name: ' ogre', keywords: ['monster'] },
      { emoji: '👺', name: ' goblin', keywords: ['monster'] },
      { emoji: '👻', name: ' ghost', keywords: ['ghost', 'halloween'] },
      { emoji: '👽', name: ' alien', keywords: ['alien', 'ufo'] },
      { emoji: '🤖', name: ' robot', keywords: ['robot'] },
      { emoji: '😺', name: ' grinning cat', keywords: ['cat', 'smile'] },
      { emoji: '😸', name: ' grinning cat with smiling eyes', keywords: ['cat', 'smile'] },
      { emoji: '😹', name: ' cat with tears of joy', keywords: ['cat', 'laugh'] },
      { emoji: '😻', name: ' smiling cat with heart-eyes', keywords: ['cat', 'love'] },
      { emoji: '😼', name: ' cat with wry smile', keywords: ['cat', 'smirk'] },
      { emoji: '😽', name: ' kissing cat', keywords: ['cat', 'kiss'] },
      { emoji: '🙀', name: ' weary cat', keywords: ['cat', 'tired'] },
      { emoji: '😿', name: ' crying cat', keywords: ['cat', 'cry'] },
      { emoji: '😾', name: ' pouting cat', keywords: ['cat', 'angry'] },
    ]
  },
  {
    label: '手势与身体',
    items: [
      { emoji: '👋', name: ' waving hand', keywords: ['wave', 'hello', 'bye'] },
      { emoji: '🤚', name: ' raised back of hand', keywords: ['hand'] },
      { emoji: '🖐️', name: ' hand with fingers splayed', keywords: ['hand', 'stop'] },
      { emoji: '✋', name: ' raised hand', keywords: ['hand', 'stop'] },
      { emoji: '🖖', name: ' vulcan salute', keywords: ['spock', 'star trek'] },
      { emoji: '👌', name: ' OK hand', keywords: ['ok', 'perfect'] },
      { emoji: '🤌', name: ' pinched fingers', keywords: ['italian', 'gesture'] },
      { emoji: '🤏', name: ' pinching hand', keywords: ['small', 'tiny'] },
      { emoji: '✌️', name: ' victory hand', keywords: ['peace', 'victory'] },
      { emoji: '🤞', name: ' crossed fingers', keywords: ['luck', 'cross'] },
      { emoji: '🫰', name: ' hand with index finger and thumb crossed', keywords: ['heart', 'love'] },
      { emoji: '🤟', name: ' love-you gesture', keywords: ['love', 'rock'] },
      { emoji: '🤘', name: ' sign of the horns', keywords: ['rock', 'horns'] },
      { emoji: '🤙', name: ' call me hand', keywords: ['call', 'phone'] },
      { emoji: '👍', name: ' thumbs up', keywords: ['up', 'like', 'good'] },
      { emoji: '👎', name: ' thumbs down', keywords: ['down', 'dislike'] },
      { emoji: '👊', name: ' oncoming fist', keywords: ['fist', 'punch'] },
      { emoji: '✊', name: ' raised fist', keywords: ['fist', 'power'] },
      { emoji: '🤛', name: ' left-facing fist', keywords: ['fist'] },
      { emoji: '🤜', name: ' right-facing fist', keywords: ['fist'] },
      { emoji: '👏', name: ' clapping hands', keywords: ['clap', 'applause'] },
      { emoji: '🙌', name: ' raising hands', keywords: ['celebrate', 'raise'] },
      { emoji: '🫶', name: ' heart hands', keywords: ['heart', 'love'] },
      { emoji: '👐', name: ' open hands', keywords: ['open'] },
      { emoji: '🤲', name: ' palms up together', keywords: ['pray'] },
      { emoji: '🤝', name: ' handshake', keywords: ['shake', 'deal'] },
      { emoji: '🙏', name: ' folded hands', keywords: ['pray', 'please', 'thank'] },
      { emoji: '✍️', name: ' writing hand', keywords: ['write'] },
      { emoji: '💅', name: ' nail polish', keywords: ['nail', 'care'] },
      { emoji: '🤳', name: ' selfie', keywords: ['selfie'] },
      { emoji: '💪', name: ' flexed biceps', keywords: ['muscle', 'strong'] },
      { emoji: '🦵', name: ' leg', keywords: ['leg'] },
      { emoji: '🦶', name: ' foot', keywords: ['foot'] },
      { emoji: '👂', name: ' ear', keywords: ['ear', 'listen'] },
      { emoji: '👃', name: ' nose', keywords: ['nose'] },
      { emoji: '🧠', name: ' brain', keywords: ['brain', 'mind'] },
      { emoji: '🫀', name: ' anatomical heart', keywords: ['heart'] },
      { emoji: '🫁', name: ' lungs', keywords: ['lungs'] },
      { emoji: '🦷', name: ' tooth', keywords: ['tooth'] },
      { emoji: '🦴', name: ' bone', keywords: ['bone'] },
      { emoji: '👀', name: ' eyes', keywords: ['eyes', 'look'] },
      { emoji: '👁️', name: ' eye', keywords: ['eye'] },
      { emoji: '👅', name: ' tongue', keywords: ['tongue', 'taste'] },
      { emoji: '👄', name: ' mouth', keywords: ['mouth', 'lips'] },
    ]
  },
  {
    label: '心形与情感',
    items: [
      { emoji: '❤️', name: ' red heart', keywords: ['heart', 'love'] },
      { emoji: '🩷', name: ' pink heart', keywords: ['heart', 'love', 'pink'] },
      { emoji: '🧡', name: ' orange heart', keywords: ['heart', 'love', 'orange'] },
      { emoji: '💛', name: ' yellow heart', keywords: ['heart', 'love', 'yellow'] },
      { emoji: '💚', name: ' green heart', keywords: ['heart', 'love', 'green'] },
      { emoji: '💙', name: ' blue heart', keywords: ['heart', 'love', 'blue'] },
      { emoji: '🩵', name: ' light blue heart', keywords: ['heart', 'love'] },
      { emoji: '💜', name: ' purple heart', keywords: ['heart', 'love', 'purple'] },
      { emoji: '🖤', name: ' black heart', keywords: ['heart', 'dark'] },
      { emoji: '🩶', name: ' grey heart', keywords: ['heart', 'grey'] },
      { emoji: '🤍', name: ' white heart', keywords: ['heart', 'white'] },
      { emoji: '🤎', name: ' brown heart', keywords: ['heart', 'brown'] },
      { emoji: '💔', name: ' broken heart', keywords: ['broken', 'heartbreak'] },
      { emoji: '❤️‍🔥', name: ' heart on fire', keywords: ['fire', 'passion'] },
      { emoji: '❤️‍🩹', name: ' mending heart', keywords: ['healing'] },
      { emoji: '💕', name: ' two hearts', keywords: ['hearts', 'love'] },
      { emoji: '💞', name: ' revolving hearts', keywords: ['hearts'] },
      { emoji: '💓', name: ' beating heart', keywords: ['beat'] },
      { emoji: '💗', name: ' growing heart', keywords: ['growing'] },
      { emoji: '💖', name: ' sparkling heart', keywords: ['sparkle'] },
      { emoji: '💘', name: ' heart with arrow', keywords: ['cupid', 'love'] },
      { emoji: '💝', name: ' heart with ribbon', keywords: ['gift', 'love'] },
      { emoji: '💟', name: ' heart decoration', keywords: ['heart'] },
      { emoji: '❣️', name: ' heart exclamation', keywords: ['heart', 'exclamation'] },
      { emoji: '🫂', name: ' people hugging', keywords: ['hug'] },
      { emoji: '💌', name: ' love letter', keywords: ['letter', 'love'] },
      { emoji: '💋', name: ' kiss mark', keywords: ['kiss', 'lipstick'] },
      { emoji: '💯', name: ' hundred points', keywords: ['100', 'perfect'] },
      { emoji: '💢', name: ' anger symbol', keywords: ['angry'] },
      { emoji: '💥', name: ' collision', keywords: ['boom', 'explosion'] },
      { emoji: '💫', name: ' dizzy', keywords: ['dizzy', 'star'] },
      { emoji: '💦', name: ' sweat droplets', keywords: ['sweat', 'water'] },
      { emoji: '💨', name: ' dashing away', keywords: ['dash', 'run', 'wind'] },
    ]
  },
  {
    label: '动物与自然',
    items: [
      { emoji: '🐶', name: ' dog face', keywords: ['dog', 'puppy'] },
      { emoji: '🐱', name: ' cat face', keywords: ['cat', 'kitten'] },
      { emoji: '🐭', name: ' mouse face', keywords: ['mouse'] },
      { emoji: '🐹', name: ' hamster', keywords: ['hamster'] },
      { emoji: '🐰', name: ' rabbit face', keywords: ['rabbit', 'bunny'] },
      { emoji: '🦊', name: ' fox', keywords: ['fox'] },
      { emoji: '🐻', name: ' bear', keywords: ['bear'] },
      { emoji: '🐼', name: ' panda', keywords: ['panda'] },
      { emoji: '🐨', name: ' koala', keywords: ['koala'] },
      { emoji: '🐯', name: ' tiger face', keywords: ['tiger'] },
      { emoji: '🦁', name: ' lion', keywords: ['lion'] },
      { emoji: '🐮', name: ' cow face', keywords: ['cow'] },
      { emoji: '🐷', name: ' pig face', keywords: ['pig'] },
      { emoji: '🐸', name: ' frog', keywords: ['frog'] },
      { emoji: '🐵', name: ' monkey face', keywords: ['monkey'] },
      { emoji: '🐔', name: ' chicken', keywords: ['chicken'] },
      { emoji: '🐧', name: ' penguin', keywords: ['penguin'] },
      { emoji: '🐦', name: ' bird', keywords: ['bird'] },
      { emoji: '🐤', name: ' baby chick', keywords: ['chick'] },
      { emoji: '🦅', name: ' eagle', keywords: ['eagle'] },
      { emoji: '🦉', name: ' owl', keywords: ['owl'] },
      { emoji: '🦇', name: ' bat', keywords: ['bat'] },
      { emoji: '🐺', name: ' wolf', keywords: ['wolf'] },
      { emoji: '🐗', name: ' boar', keywords: ['boar'] },
      { emoji: '🐴', name: ' horse face', keywords: ['horse'] },
      { emoji: '🦄', name: ' unicorn', keywords: ['unicorn'] },
      { emoji: '🐝', name: ' honeybee', keywords: ['bee', 'honey'] },
      { emoji: '🦋', name: ' butterfly', keywords: ['butterfly'] },
      { emoji: '🐌', name: ' snail', keywords: ['snail'] },
      { emoji: '🐞', name: ' lady beetle', keywords: ['ladybug'] },
      { emoji: '🐜', name: ' ant', keywords: ['ant'] },
      { emoji: '🪲', name: ' beetle', keywords: ['beetle'] },
      { emoji: '🦟', name: ' mosquito', keywords: ['mosquito'] },
      { emoji: '🦗', name: ' cricket', keywords: ['cricket'] },
      { emoji: '🐢', name: ' turtle', keywords: ['turtle'] },
      { emoji: '🐍', name: ' snake', keywords: ['snake'] },
      { emoji: '🦎', name: ' lizard', keywords: ['lizard'] },
      { emoji: '🐙', name: ' octopus', keywords: ['octopus'] },
      { emoji: '🦑', name: ' squid', keywords: ['squid'] },
      { emoji: '🦐', name: ' shrimp', keywords: ['shrimp'] },
      { emoji: '🐠', name: ' tropical fish', keywords: ['fish'] },
      { emoji: '🐟', name: ' fish', keywords: ['fish'] },
      { emoji: '🐡', name: ' blowfish', keywords: ['blowfish'] },
      { emoji: '🐬', name: ' dolphin', keywords: ['dolphin'] },
      { emoji: '🐳', name: ' spouting whale', keywords: ['whale'] },
      { emoji: '🐋', name: ' whale', keywords: ['whale'] },
      { emoji: '🦈', name: ' shark', keywords: ['shark'] },
      { emoji: '🐊', name: ' crocodile', keywords: ['crocodile'] },
      { emoji: '🦭', name: ' seal', keywords: ['seal'] },
      { emoji: '🦩', name: ' flamingo', keywords: ['flamingo'] },
      { emoji: '🦚', name: ' peacock', keywords: ['peacock'] },
      { emoji: '🦜', name: ' parrot', keywords: ['parrot'] },
      { emoji: '🐈', name: ' cat', keywords: ['cat'] },
      { emoji: '🪴', name: ' potted plant', keywords: ['plant'] },
      { emoji: '🌵', name: ' cactus', keywords: ['cactus'] },
      { emoji: '🌲', name: ' evergreen tree', keywords: ['tree', 'pine'] },
      { emoji: '🌳', name: ' deciduous tree', keywords: ['tree'] },
      { emoji: '🌴', name: ' palm tree', keywords: ['palm', 'tropical'] },
      { emoji: '🌱', name: ' seedling', keywords: ['seed', 'sprout'] },
      { emoji: '🌿', name: ' herb', keywords: ['herb', 'leaf'] },
      { emoji: '☘️', name: ' shamrock', keywords: ['clover', 'irish'] },
      { emoji: '🍀', name: ' four leaf clover', keywords: ['lucky', 'clover'] },
      { emoji: '🍁', name: ' maple leaf', keywords: ['maple', 'canada'] },
      { emoji: '🍂', name: ' fallen leaf', keywords: ['leaf', 'autumn'] },
      { emoji: '🍃', name: ' leaf fluttering in wind', keywords: ['leaf', 'wind'] },
      { emoji: '🌸', name: ' cherry blossom', keywords: ['flower', 'spring'] },
      { emoji: '💐', name: ' bouquet', keywords: ['flowers'] },
      { emoji: '🌹', name: ' rose', keywords: ['rose', 'flower'] },
      { emoji: '🌺', name: ' hibiscus', keywords: ['flower'] },
      { emoji: '🌻', name: ' sunflower', keywords: ['flower', 'sun'] },
      { emoji: '🌼', name: ' blossom', keywords: ['flower'] },
      { emoji: '🌷', name: ' tulip', keywords: ['tulip', 'flower'] },
      { emoji: '🌾', name: ' sheaf of rice', keywords: ['rice', 'grain'] },
      { emoji: '🍄', name: ' mushroom', keywords: ['mushroom'] },
      { emoji: '🌰', name: ' chestnut', keywords: ['chestnut'] },
    ]
  },
  {
    label: '食物与饮料',
    items: [
      { emoji: '🍏', name: ' green apple', keywords: ['apple', 'fruit'] },
      { emoji: '🍎', name: ' red apple', keywords: ['apple', 'fruit'] },
      { emoji: '🍐', name: ' pear', keywords: ['pear'] },
      { emoji: '🍊', name: ' tangerine', keywords: ['orange', 'fruit'] },
      { emoji: '🍋', name: ' lemon', keywords: ['lemon'] },
      { emoji: '🍌', name: ' banana', keywords: ['banana'] },
      { emoji: '🍉', name: ' watermelon', keywords: ['watermelon'] },
      { emoji: '🍇', name: ' grapes', keywords: ['grape'] },
      { emoji: '🍓', name: ' strawberry', keywords: ['strawberry'] },
      { emoji: '🫐', name: ' blueberries', keywords: ['blueberry'] },
      { emoji: '🍈', name: ' melon', keywords: ['melon'] },
      { emoji: '🍒', name: ' cherries', keywords: ['cherry'] },
      { emoji: '🍑', name: ' peach', keywords: ['peach'] },
      { emoji: '🥭', name: ' mango', keywords: ['mango'] },
      { emoji: '🍍', name: ' pineapple', keywords: ['pineapple'] },
      { emoji: '🥥', name: ' coconut', keywords: ['coconut'] },
      { emoji: '🥝', name: ' kiwi fruit', keywords: ['kiwi'] },
      { emoji: '🍅', name: ' tomato', keywords: ['tomato'] },
      { emoji: '🥑', name: ' avocado', keywords: ['avocado'] },
      { emoji: '🍆', name: ' eggplant', keywords: ['eggplant', 'aubergine'] },
      { emoji: '🥔', name: ' potato', keywords: ['potato'] },
      { emoji: '🥕', name: ' carrot', keywords: ['carrot'] },
      { emoji: '🌽', name: ' ear of corn', keywords: ['corn'] },
      { emoji: '🥦', name: ' broccoli', keywords: ['broccoli'] },
      { emoji: '🫑', name: ' bell pepper', keywords: ['pepper'] },
      { emoji: '🥒', name: ' cucumber', keywords: ['cucumber'] },
      { emoji: '🥬', name: ' leafy green', keywords: ['lettuce', 'salad'] },
      { emoji: '🧄', name: ' garlic', keywords: ['garlic'] },
      { emoji: '🧅', name: ' onion', keywords: ['onion'] },
      { emoji: '🍞', name: ' bread', keywords: ['bread', 'toast'] },
      { emoji: '🥐', name: ' croissant', keywords: ['croissant'] },
      { emoji: '🥖', name: ' baguette bread', keywords: ['bread'] },
      { emoji: '🥨', name: ' pretzel', keywords: ['pretzel'] },
      { emoji: '🧀', name: ' cheese wedge', keywords: ['cheese'] },
      { emoji: '🍳', name: ' cooking', keywords: ['egg', 'fry'] },
      { emoji: '🥞', name: ' pancakes', keywords: ['pancake'] },
      { emoji: '🧇', name: ' waffle', keywords: ['waffle'] },
      { emoji: '🥓', name: ' bacon', keywords: ['bacon'] },
      { emoji: '🍔', name: ' hamburger', keywords: ['burger'] },
      { emoji: '🍟', name: ' french fries', keywords: ['fries'] },
      { emoji: '🍕', name: ' pizza', keywords: ['pizza'] },
      { emoji: '🌭', name: ' hot dog', keywords: ['hotdog'] },
      { emoji: '🥪', name: ' sandwich', keywords: ['sandwich'] },
      { emoji: '🌮', name: ' taco', keywords: ['taco'] },
      { emoji: '🌯', name: ' burrito', keywords: ['burrito'] },
      { emoji: '🥙', name: ' stuffed flatbread', keywords: ['wrap'] },
      { emoji: '🧆', name: ' falafel', keywords: ['falafel'] },
      { emoji: '🥚', name: ' egg', keywords: ['egg'] },
      { emoji: '🥗', name: ' green salad', keywords: ['salad'] },
      { emoji: '🍿', name: ' popcorn', keywords: ['popcorn'] },
      { emoji: '🧈', name: ' butter', keywords: ['butter'] },
      { emoji: '🍱', name: ' bento box', keywords: ['bento'] },
      { emoji: '🍘', name: ' rice cracker', keywords: ['cracker'] },
      { emoji: '🍙', name: ' rice ball', keywords: ['rice'] },
      { emoji: '🍚', name: ' cooked rice', keywords: ['rice'] },
      { emoji: '🍛', name: ' curry rice', keywords: ['curry'] },
      { emoji: '🍜', name: ' steaming bowl', keywords: ['noodle', 'ramen'] },
      { emoji: '🍝', name: ' spaghetti', keywords: ['pasta'] },
      { emoji: '🍠', name: ' roasted sweet potato', keywords: ['potato'] },
      { emoji: '🍢', name: ' oden', keywords: ['skewer'] },
      { emoji: '🍣', name: ' sushi', keywords: ['sushi'] },
      { emoji: '🍤', name: ' fried shrimp', keywords: ['shrimp', 'tempura'] },
      { emoji: '🍥', name: ' fish cake with swirl', keywords: ['fish', 'cake'] },
      { emoji: '🥮', name: ' moon cake', keywords: ['mooncake'] },
      { emoji: '🍡', name: ' dango', keywords: ['dango'] },
      { emoji: '🥟', name: ' dumpling', keywords: ['dumpling'] },
      { emoji: '🥠', name: ' fortune cookie', keywords: ['fortune', 'cookie'] },
      { emoji: '🥡', name: ' takeout box', keywords: ['takeout'] },
      { emoji: '🍦', name: ' soft ice cream', keywords: ['ice cream'] },
      { emoji: '🍧', name: ' shaved ice', keywords: ['ice'] },
      { emoji: '🍨', name: ' ice cream', keywords: ['ice cream'] },
      { emoji: '🍩', name: ' doughnut', keywords: ['donut'] },
      { emoji: '🍪', name: ' cookie', keywords: ['cookie'] },
      { emoji: '🎂', name: ' birthday cake', keywords: ['cake', 'birthday'] },
      { emoji: '🍰', name: ' shortcake', keywords: ['cake'] },
      { emoji: '🧁', name: ' cupcake', keywords: ['cupcake'] },
      { emoji: '🥧', name: ' pie', keywords: ['pie'] },
      { emoji: '🍫', name: ' chocolate bar', keywords: ['chocolate'] },
      { emoji: '🍬', name: ' candy', keywords: ['candy'] },
      { emoji: '🍭', name: ' lollipop', keywords: ['lollipop'] },
      { emoji: '🍮', name: ' custard', keywords: ['pudding'] },
      { emoji: '🍯', name: ' honey pot', keywords: ['honey'] },
      { emoji: '☕', name: ' hot beverage', keywords: ['coffee', 'tea'] },
      { emoji: '🫖', name: ' teapot', keywords: ['tea'] },
      { emoji: '🍵', name: ' teacup without handle', keywords: ['tea', 'green'] },
      { emoji: '🧋', name: ' bubble tea', keywords: ['boba', 'milk tea'] },
      { emoji: '🥤', name: ' cup with straw', keywords: ['soda', 'drink'] },
      { emoji: '🧃', name: ' beverage box', keywords: ['juice'] },
      { emoji: '🍶', name: ' sake', keywords: ['sake', 'rice wine'] },
      { emoji: '🍺', name: ' beer mug', keywords: ['beer'] },
      { emoji: '🍻', name: ' clinking beer mugs', keywords: ['beer', 'cheers'] },
      { emoji: '🥂', name: ' clinking glasses', keywords: ['cheers', 'champagne'] },
      { emoji: '🍷', name: ' wine glass', keywords: ['wine'] },
      { emoji: '🥃', name: ' tumbler glass', keywords: ['whiskey'] },
      { emoji: '🍸', name: ' cocktail glass', keywords: ['cocktail'] },
      { emoji: '🍹', name: ' tropical drink', keywords: ['tropical'] },
      { emoji: '🧊', name: ' ice', keywords: ['ice', 'cube'] },
    ]
  },
  {
    label: '活动与旅行',
    items: [
      { emoji: '⚽', name: ' soccer ball', keywords: ['soccer', 'football'] },
      { emoji: '🏀', name: ' basketball', keywords: ['basketball'] },
      { emoji: '🏈', name: ' american football', keywords: ['football'] },
      { emoji: '⚾', name: ' baseball', keywords: ['baseball'] },
      { emoji: '🎾', name: ' tennis', keywords: ['tennis'] },
      { emoji: '🏐', name: ' volleyball', keywords: ['volleyball'] },
      { emoji: '🏉', name: ' rugby football', keywords: ['rugby'] },
      { emoji: '🎱', name: ' pool 8 ball', keywords: ['billiard', '8ball'] },
      { emoji: '🏓', name: ' ping pong', keywords: ['table tennis'] },
      { emoji: '🏸', name: ' badminton', keywords: ['badminton'] },
      { emoji: '🥊', name: ' boxing glove', keywords: ['boxing'] },
      { emoji: '🥋', name: ' martial arts uniform', keywords: ['karate'] },
      { emoji: '⛳', name: ' flag in hole', keywords: ['golf'] },
      { emoji: '🎣', name: ' fishing pole', keywords: ['fishing'] },
      { emoji: '🤿', name: ' diving mask', keywords: ['diving'] },
      { emoji: '🎿', name: ' skis', keywords: ['ski'] },
      { emoji: '🏂', name: ' snowboarder', keywords: ['snowboard'] },
      { emoji: '🏃', name: ' running person', keywords: ['run', 'sprint'] },
      { emoji: '🚶', name: ' walking', keywords: ['walk'] },
      { emoji: '🏋️', name: ' weight lifter', keywords: ['gym', 'weight'] },
      { emoji: '🧘', name: ' person in lotus position', keywords: ['yoga', 'meditate'] },
      { emoji: '🎯', name: ' direct hit', keywords: ['target', 'bullseye'] },
      { emoji: '🎮', name: ' video game', keywords: ['game', 'controller'] },
      { emoji: '🎰', name: ' slot machine', keywords: ['casino'] },
      { emoji: '🎲', name: ' game die', keywords: ['dice'] },
      { emoji: '♟️', name: ' chess pawn', keywords: ['chess'] },
      { emoji: '🎭', name: ' performing arts', keywords: ['theater', 'drama'] },
      { emoji: '🎨', name: ' artist palette', keywords: ['art', 'paint'] },
      { emoji: '🎬', name: ' clapper board', keywords: ['movie', 'film'] },
      { emoji: '🎤', name: ' microphone', keywords: ['mic', 'sing'] },
      { emoji: '🎧', name: ' headphone', keywords: ['headphone', 'music'] },
      { emoji: '🎵', name: ' musical note', keywords: ['music', 'note'] },
      { emoji: '🎶', name: ' musical notes', keywords: ['music'] },
      { emoji: '🎼', name: ' musical score', keywords: ['music'] },
      { emoji: '🎹', name: ' musical keyboard', keywords: ['piano'] },
      { emoji: '🥁', name: ' drum', keywords: ['drum'] },
      { emoji: '🎷', name: ' saxophone', keywords: ['sax'] },
      { emoji: '🎺', name: ' trumpet', keywords: ['trumpet'] },
      { emoji: '🎸', name: ' guitar', keywords: ['guitar'] },
      { emoji: '🎻', name: ' violin', keywords: ['violin'] },
      { emoji: '🚗', name: ' car', keywords: ['car', 'auto'] },
      { emoji: '🚕', name: ' taxi', keywords: ['taxi'] },
      { emoji: '🚙', name: ' SUV', keywords: ['car', 'suv'] },
      { emoji: '🚌', name: ' bus', keywords: ['bus'] },
      { emoji: '🚎', name: ' trolleybus', keywords: ['bus'] },
      { emoji: '🚓', name: ' police car', keywords: ['police'] },
      { emoji: '🚑', name: ' ambulance', keywords: ['ambulance'] },
      { emoji: '🚒', name: ' fire engine', keywords: ['fire', 'truck'] },
      { emoji: '🚐', name: ' minibus', keywords: ['van'] },
      { emoji: '🚲', name: ' bicycle', keywords: ['bike', 'cycle'] },
      { emoji: '🛴', name: ' kick scooter', keywords: ['scooter'] },
      { emoji: '🛵', name: ' motor scooter', keywords: ['scooter'] },
      { emoji: '🏍️', name: ' motorcycle', keywords: ['motorcycle'] },
      { emoji: '✈️', name: ' airplane', keywords: ['plane', 'flight'] },
      { emoji: '🚀', name: ' rocket', keywords: ['rocket', 'space'] },
      { emoji: '🛸', name: ' flying saucer', keywords: ['ufo'] },
      { emoji: '🚁', name: ' helicopter', keywords: ['helicopter'] },
      { emoji: '🚢', name: ' ship', keywords: ['ship', 'boat'] },
      { emoji: '🛶', name: ' canoe', keywords: ['canoe', 'boat'] },
      { emoji: '⛵', name: ' sailboat', keywords: ['sailboat', 'yacht'] },
      { emoji: '🚂', name: ' locomotive', keywords: ['train'] },
      { emoji: '🚃', name: ' railway car', keywords: ['train'] },
      { emoji: '🚄', name: ' high-speed train', keywords: ['train'] },
      { emoji: '🚅', name: ' bullet train', keywords: ['train', 'shinkansen'] },
      { emoji: '🚇', name: ' metro', keywords: ['subway'] },
      { emoji: '🚉', name: ' station', keywords: ['station'] },
      { emoji: '🗺️', name: ' world map', keywords: ['map', 'world'] },
      { emoji: '🏔️', name: ' snow-capped mountain', keywords: ['mountain'] },
      { emoji: '🏖️', name: ' beach with umbrella', keywords: ['beach'] },
      { emoji: '🏝️', name: ' desert island', keywords: ['island'] },
      { emoji: '🏜️', name: ' desert', keywords: ['desert'] },
      { emoji: '🌋', name: ' volcano', keywords: ['volcano'] },
      { emoji: '🗽', name: ' statue of liberty', keywords: ['liberty'] },
      { emoji: '🏯', name: ' japanese castle', keywords: ['castle'] },
      { emoji: '🏰', name: ' castle', keywords: ['castle'] },
      { emoji: '🎡', name: ' ferris wheel', keywords: ['ferris', 'wheel'] },
      { emoji: '🎢', name: ' roller coaster', keywords: ['roller', 'coaster'] },
      { emoji: '🎠', name: ' carousel horse', keywords: ['carousel'] },
      { emoji: '⛺', name: ' tent', keywords: ['camping', 'tent'] },
      { emoji: '🌇', name: ' sunset', keywords: ['sunset', 'dusk'] },
      { emoji: '🌆', name: ' cityscape at dusk', keywords: ['city', 'dusk'] },
      { emoji: '🌃', name: ' night with stars', keywords: ['night', 'star'] },
      { emoji: '🌉', name: ' bridge at night', keywords: ['bridge', 'night'] },
      { emoji: '🌌', name: ' milky way', keywords: ['milky', 'galaxy'] },
      { emoji: '🌈', name: ' rainbow', keywords: ['rainbow'] },
      { emoji: '☀️', name: ' sun', keywords: ['sun', 'sunny'] },
      { emoji: '🌞', name: ' sun with face', keywords: ['sun'] },
      { emoji: '🌝', name: ' full moon face', keywords: ['moon'] },
      { emoji: '🌙', name: ' crescent moon', keywords: ['moon', 'night'] },
      { emoji: '⭐', name: ' star', keywords: ['star'] },
      { emoji: '🌟', name: ' glowing star', keywords: ['star', 'glow'] },
      { emoji: '☁️', name: ' cloud', keywords: ['cloud'] },
      { emoji: '⛅', name: ' sun behind cloud', keywords: ['cloud', 'partly'] },
      { emoji: '🌤️', name: ' sun behind small cloud', keywords: ['sun', 'cloud'] },
      { emoji: '🌥️', name: ' sun behind large cloud', keywords: ['cloud', 'overcast'] },
      { emoji: '🌦️', name: ' sun behind rain cloud', keywords: ['rain', 'sun'] },
      { emoji: '🌧️', name: ' cloud with rain', keywords: ['rain'] },
      { emoji: '⛈️', name: ' cloud with lightning and rain', keywords: ['storm'] },
      { emoji: '🌩️', name: ' cloud with lightning', keywords: ['lightning'] },
      { emoji: '🌨️', name: ' cloud with snow', keywords: ['snow'] },
      { emoji: '❄️', name: ' snowflake', keywords: ['snow', 'winter'] },
      { emoji: '🌪️', name: ' tornado', keywords: ['tornado'] },
      { emoji: '🌫️', name: ' fog', keywords: ['fog'] },
      { emoji: '🌊', name: ' water wave', keywords: ['wave', 'ocean', 'sea'] },
      { emoji: '💧', name: ' droplet', keywords: ['water', 'drop'] },
      { emoji: '🔥', name: ' fire', keywords: ['fire', 'flame', 'hot'] },
    ]
  },
  {
    label: '物体与符号',
    items: [
      { emoji: '⌚', name: ' watch', keywords: ['watch', 'time'] },
      { emoji: '📱', name: ' mobile phone', keywords: ['phone', 'smartphone'] },
      { emoji: '💻', name: ' laptop', keywords: ['computer', 'laptop'] },
      { emoji: '⌨️', name: ' keyboard', keywords: ['keyboard'] },
      { emoji: '🖥️', name: ' desktop computer', keywords: ['computer', 'desktop'] },
      { emoji: '🖨️', name: ' printer', keywords: ['printer'] },
      { emoji: '🖱️', name: ' computer mouse', keywords: ['mouse'] },
      { emoji: '💽', name: ' computer disk', keywords: ['disk'] },
      { emoji: '💾', name: ' floppy disk', keywords: ['save'] },
      { emoji: '💿', name: ' optical disk', keywords: ['cd', 'dvd'] },
      { emoji: '📀', name: ' dvd', keywords: ['dvd'] },
      { emoji: '📷', name: ' camera', keywords: ['camera', 'photo'] },
      { emoji: '📸', name: ' camera with flash', keywords: ['camera', 'photo'] },
      { emoji: '📹', name: ' video camera', keywords: ['video'] },
      { emoji: '🎥', name: ' movie camera', keywords: ['camera', 'movie'] },
      { emoji: '📽️', name: ' film projector', keywords: ['projector'] },
      { emoji: '📺', name: ' television', keywords: ['tv', 'television'] },
      { emoji: '📻', name: ' radio', keywords: ['radio'] },
      { emoji: '🔊', name: ' speaker high volume', keywords: ['volume', 'loud'] },
      { emoji: '🔇', name: ' muted speaker', keywords: ['mute', 'silent'] },
      { emoji: '🔔', name: ' bell', keywords: ['bell', 'notification'] },
      { emoji: '🔕', name: ' bell with slash', keywords: ['silent'] },
      { emoji: '📢', name: ' loudspeaker', keywords: ['announce'] },
      { emoji: '📣', name: ' megaphone', keywords: ['megaphone'] },
      { emoji: '⏰', name: ' alarm clock', keywords: ['alarm', 'time'] },
      { emoji: '⏳', name: ' hourglass not done', keywords: ['time', 'sand'] },
      { emoji: '⌛', name: ' hourglass done', keywords: ['time'] },
      { emoji: '📡', name: ' satellite antenna', keywords: ['satellite', 'signal'] },
      { emoji: '🔋', name: ' battery', keywords: ['battery', 'power'] },
      { emoji: '🔌', name: ' electric plug', keywords: ['plug'] },
      { emoji: '💡', name: ' light bulb', keywords: ['idea', 'light'] },
      { emoji: '🔦', name: ' flashlight', keywords: ['flashlight', 'torch'] },
      { emoji: '🕯️', name: ' candle', keywords: ['candle'] },
      { emoji: '💰', name: ' money bag', keywords: ['money', 'bag'] },
      { emoji: '💳', name: ' credit card', keywords: ['card', 'payment'] },
      { emoji: '💵', name: ' dollar banknote', keywords: ['money', 'dollar'] },
      { emoji: '💴', name: ' yen banknote', keywords: ['yen', 'money'] },
      { emoji: '💶', name: ' euro banknote', keywords: ['euro', 'money'] },
      { emoji: '💷', name: ' pound banknote', keywords: ['pound', 'money'] },
      { emoji: '🪙', name: ' coin', keywords: ['coin'] },
      { emoji: '💎', name: ' gem stone', keywords: ['diamond', 'jewel'] },
      { emoji: '📦', name: ' package', keywords: ['package', 'box'] },
      { emoji: '📫', name: ' mailbox', keywords: ['mail', 'letter'] },
      { emoji: '📬', name: ' mailbox with mail', keywords: ['mail'] },
      { emoji: '📮', name: ' postbox', keywords: ['post'] },
      { emoji: '✉️', name: ' envelope', keywords: ['email', 'letter'] },
      { emoji: '📝', name: ' memo', keywords: ['note', 'memo'] },
      { emoji: '📄', name: ' page facing up', keywords: ['document'] },
      { emoji: '📃', name: ' page with curl', keywords: ['document'] },
      { emoji: '📑', name: ' bookmark tabs', keywords: ['bookmark'] },
      { emoji: '📊', name: ' bar chart', keywords: ['chart', 'stats'] },
      { emoji: '📈', name: ' chart increasing', keywords: ['chart', 'growth'] },
      { emoji: '📉', name: ' chart decreasing', keywords: ['chart', 'down'] },
      { emoji: '📋', name: ' clipboard', keywords: ['clipboard'] },
      { emoji: '📌', name: ' pushpin', keywords: ['pin'] },
      { emoji: '📍', name: ' round pushpin', keywords: ['pin', 'location'] },
      { emoji: '📎', name: ' paperclip', keywords: ['clip'] },
      { emoji: '🖇️', name: ' linked paperclips', keywords: ['clip'] },
      { emoji: '✂️', name: ' scissors', keywords: ['scissors', 'cut'] },
      { emoji: '🔗', name: ' link', keywords: ['link', 'url'] },
      { emoji: '📐', name: ' triangular ruler', keywords: ['ruler'] },
      { emoji: '📏', name: ' straight ruler', keywords: ['ruler'] },
      { emoji: '🔒', name: ' locked', keywords: ['lock', 'secure'] },
      { emoji: '🔓', name: ' unlocked', keywords: ['lock', 'open'] },
      { emoji: '🔑', name: ' key', keywords: ['key', 'password'] },
      { emoji: '🔨', name: ' hammer', keywords: ['hammer', 'tool'] },
      { emoji: '🪓', name: ' axe', keywords: ['axe'] },
      { emoji: '🔧', name: ' wrench', keywords: ['wrench', 'tool'] },
      { emoji: '🔩', name: ' nut and bolt', keywords: ['bolt'] },
      { emoji: '⚙️', name: ' gear', keywords: ['gear', 'settings'] },
      { emoji: '🧰', name: ' toolbox', keywords: ['toolbox', 'tools'] },
      { emoji: '🧲', name: ' magnet', keywords: ['magnet'] },
      { emoji: '🔬', name: ' microscope', keywords: ['microscope', 'science'] },
      { emoji: '🔭', name: ' telescope', keywords: ['telescope'] },
      { emoji: '📡', name: ' satellite antenna', keywords: ['satellite'] },
      { emoji: '💉', name: ' syringe', keywords: ['needle', 'injection'] },
      { emoji: '💊', name: ' pill', keywords: ['medicine', 'pill'] },
      { emoji: '🩹', name: ' adhesive bandage', keywords: ['bandaid'] },
      { emoji: '🩺', name: ' stethoscope', keywords: ['stethoscope', 'doctor'] },
      { emoji: '🚿', name: ' shower', keywords: ['shower'] },
      { emoji: '🛁', name: ' bathtub', keywords: ['bath', 'bathtub'] },
      { emoji: '🧼', name: ' soap', keywords: ['soap'] },
      { emoji: '🧽', name: ' sponge', keywords: ['sponge'] },
      { emoji: '🧴', name: ' lotion bottle', keywords: ['lotion'] },
      { emoji: '🪥', name: ' toothbrush', keywords: ['toothbrush'] },
      { emoji: '🪒', name: ' razor', keywords: ['razor'] },
      { emoji: '🛏️', name: ' bed', keywords: ['bed'] },
      { emoji: '🪑', name: ' chair', keywords: ['chair'] },
      { emoji: '🚽', name: ' toilet', keywords: ['toilet'] },
      { emoji: '🧻', name: ' roll of paper', keywords: ['toilet paper'] },
      { emoji: '🪟', name: ' window', keywords: ['window'] },
      { emoji: '🚪', name: ' door', keywords: ['door'] },
      { emoji: '🛗', name: ' elevator', keywords: ['elevator', 'lift'] },
      { emoji: '🪞', name: ' mirror', keywords: ['mirror'] },
      { emoji: '🏠', name: ' house', keywords: ['house', 'home'] },
      { emoji: '🏡', name: ' house with garden', keywords: ['house', 'home', 'garden'] },
      { emoji: '🏢', name: ' office building', keywords: ['office'] },
      { emoji: '🏣', name: ' japanese post office', keywords: ['post'] },
      { emoji: '🏥', name: ' hospital', keywords: ['hospital'] },
      { emoji: '🏦', name: ' bank', keywords: ['bank'] },
      { emoji: '🏪', name: ' convenience store', keywords: ['store'] },
      { emoji: '🏫', name: ' school', keywords: ['school'] },
      { emoji: '🏩', name: ' love hotel', keywords: ['hotel'] },
      { emoji: '💒', name: ' wedding', keywords: ['wedding'] },
      { emoji: '⛪', name: ' church', keywords: ['church'] },
      { emoji: '🕌', name: ' mosque', keywords: ['mosque'] },
      { emoji: '🕍', name: ' synagogue', keywords: ['synagogue'] },
      { emoji: '🛕', name: ' hindu temple', keywords: ['temple'] },
      { emoji: '🕋', name: ' kaaba', keywords: ['kaaba'] },
      { emoji: '🎪', name: ' circus tent', keywords: ['circus'] },
      { emoji: '🎭', name: ' performing arts', keywords: ['theater'] },
      { emoji: '🎨', name: ' artist palette', keywords: ['art'] },
      { emoji: '🗼', name: ' tokyo tower', keywords: ['tokyo', 'tower'] },
      { emoji: '🗾', name: ' map of japan', keywords: ['japan'] },
      { emoji: '🎌', name: ' crossed flags', keywords: ['japan'] },
      { emoji: '🏁', name: ' chequered flag', keywords: ['finish', 'race'] },
      { emoji: '🚩', name: ' triangular flag', keywords: ['flag'] },
      { emoji: '🎀', name: ' ribbon', keywords: ['ribbon'] },
      { emoji: '🎁', name: ' wrapped gift', keywords: ['gift', 'present'] },
      { emoji: '🎉', name: ' party popper', keywords: ['party', 'tada'] },
      { emoji: '🎊', name: ' confetti ball', keywords: ['confetti'] },
      { emoji: '🎈', name: ' balloon', keywords: ['balloon'] },
      { emoji: '🎃', name: ' jack-o-lantern', keywords: ['halloween', 'pumpkin'] },
      { emoji: '🎄', name: ' christmas tree', keywords: ['christmas'] },
      { emoji: '🎆', name: ' fireworks', keywords: ['fireworks'] },
      { emoji: '🧧', name: ' red envelope', keywords: ['red packet', 'angpao'] },
      { emoji: '🧨', name: ' firecracker', keywords: ['firecracker'] },
      { emoji: '✨', name: ' sparkles', keywords: ['sparkle', 'shiny'] },
      { emoji: '🎓', name: ' graduation cap', keywords: ['graduation'] },
      { emoji: '🏆', name: ' trophy', keywords: ['trophy', 'win'] },
      { emoji: '🥇', name: ' 1st place medal', keywords: ['gold', 'first'] },
      { emoji: '🥈', name: ' 2nd place medal', keywords: ['silver', 'second'] },
      { emoji: '🥉', name: ' 3rd place medal', keywords: ['bronze', 'third'] },
      { emoji: '🪄', name: ' magic wand', keywords: ['magic'] },
      { emoji: '🔮', name: ' crystal ball', keywords: ['fortune', 'future'] },
      { emoji: '🕹️', name: ' joystick', keywords: ['joystick'] },
      { emoji: '🗿', name: ' moai', keywords: ['statue', 'easter'] },
      { emoji: '🪪', name: ' identification card', keywords: ['id', 'card'] },
      { emoji: '🪪', name: ' identification card', keywords: ['id card'] },
      { emoji: '🎵', name: ' musical note', keywords: ['music', 'note'] },
      { emoji: '🎶', name: ' musical notes', keywords: ['music'] },
    ]
  },
]

/** 将所有 emoji 拍平成一个数组 */
export function getAllEmojis(): EmojiItem[] {
  return emojiCategories.flatMap(c => c.items)
}

/** 根据查询词过滤 emoji */
export function filterEmojis(query: string): EmojiItem[] {
  if (!query) return getAllEmojis()
  const q = query.toLowerCase()
  return getAllEmojis().filter(
    item =>
      item.name.toLowerCase().includes(q) ||
      item.keywords.some(k => k.includes(q))
  )
}
